package com.example.network

object HttpStatus {

    val SC_ACCEPTED = 202
    val SC_BAD_GATEWAY = 502
    val SC_BAD_REQUEST = 400
    val SC_CONFLICT = 409
    val SC_CONTINUE = 100
    val SC_CREATED = 201
    val SC_EXPECTATION_FAILED = 417
    val SC_FAILED_DEPENDENCY = 424
    val SC_FORBIDDEN = 403
    val SC_GATEWAY_TIMEOUT = 504
    val SC_GONE = 410
    val SC_HTTP_VERSION_NOT_SUPPORTED = 505
    val SC_INSUFFICIENT_SPACE_ON_RESOURCE = 419
    val SC_INSUFFICIENT_STORAGE = 507
    val SC_INTERNAL_SERVER_ERROR = 500
    val SC_LENGTH_REQUIRED = 411
    val SC_LOCKED = 423
    val SC_METHOD_FAILURE = 420
    val SC_METHOD_NOT_ALLOWED = 405
    val SC_MOVED_PERMANENTLY = 301
    val SC_MOVED_TEMPORARILY = 302
    val SC_MULTIPLE_CHOICES = 300
    val SC_MULTI_STATUS = 207
    val SC_NON_AUTHORITATIVE_INFORMATION = 203
    val SC_NOT_ACCEPTABLE = 406
    val SC_NOT_FOUND = 404
    val SC_NOT_IMPLEMENTED = 501
    val SC_NOT_MODIFIED = 304
    val SC_NO_CONTENT = 204
    val SC_OK = 200
    val SC_PARTIAL_CONTENT = 206
    val SC_PAYMENT_REQUIRED = 402
    val SC_PRECONDITION_FAILED = 412
    val SC_PROCESSING = 102
    val SC_PROXY_AUTHENTICATION_REQUIRED = 407
    val SC_REQUESTED_RANGE_NOT_SATISFIABLE = 416
    val SC_REQUEST_TIMEOUT = 408
    val SC_REQUEST_TOO_LONG = 413
    val SC_REQUEST_URI_TOO_LONG = 414
    val SC_RESET_CONTENT = 205
    val SC_SEE_OTHER = 303
    val SC_SERVICE_UNAVAILABLE = 503
    val SC_SWITCHING_PROTOCOLS = 101
    val SC_TEMPORARY_REDIRECT = 307
    val SC_UNAUTHORIZED = 401
    val SC_UNPROCESSABLE_ENTITY = 422
    val SC_UNSUPPORTED_MEDIA_TYPE = 415
    val SC_USE_PROXY = 305
}
